version: '3.4'

services:
  contactdb:
    image: mongo
    ports:
    - "27017:27017"
    
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

  contact.api:
    image: ${DOCKER_REGISTRY-}contactapi
    build:
      context: .
      dockerfile: Contact.API/Dockerfile

  report.api:
    image: ${DOCKER_REGISTRY-}reportapi
    build:
      context: .
      dockerfile: Report.API/Dockerfile
      
volumes:
  mongo_data:

